### ISSUE TITLE
Add depth flag.

### ISSUE THREAD

**Issue by rozzzly** [wilk/thanc#1]
You should add a `--depth` flag. This would limit the depth to which `thanc` traverses the dependency tree.

For example:
`thank --depth=1` only star dependencies defined in `package.json`
`thank --depth=2` star the dependencies defined in `package.json` and the dependencies defined in their `package.json`

Omitting the depth flag would default to the current behavior of traversing the entire dependency tree.

**Comment by wilk** [comment]
Hi @rozzzly,

traversing and starring the entire dependency tree is actually the main feature of thanc.
[thank-you-stars](https://www.npmjs.com/package/thank-you-stars) lets you to star the solely package.json dependencies list (your --depth=1) and I didn't want to create duplicates.
The other edge case is to star the whole dependency tree.

The dependency tree could be very deep: what kind of situation requires the user to specify --depth=2 or --depth=3 or 4?
I mean: excluding those 2 edge cases listed above, what's the real need to specify the others levels?

**Comment by rozzzly** [comment]
Personally, I just don't have the desire to star 1000s of micro-modules, but a hundred or so... maybe.

I suggest you read [something by David Haney](http://www.haneycodes.net/npm-left-pad-have-we-forgotten-how-to-program/).

> There’s a package called `isArray` that has 880,000 downloads a day, and 18 million downloads in February of 2016. It has **72 dependent NPM packages**. Here’s its entire **1 line of code**:
> ```javascript
> return toString.call(arr) == '[object Array]';

I'm sorry, but packages like `isArray`—which is in my `./node_modules`—do not deserve my stars and I don't want to perpetuate garbage like that in the registry. The farther into your dependency tree you travel, the more strange junk you will find. Conversely, the closer to your own `package.json` you stay, the more relevant to your app the dependencies will be.

> I didn't want to create duplicates

You wouldn't be. `thank-you-stars` doesn't offer a depth option either; you'd be allowing people who more freedom.

**Comment by wilk** [comment]
I see your point but I don't think this is the way to get rid of it.
`node_modules` weight is one of the most debated topic and using a depth option to avoid starring unwanted packages, it just doesn't work, because you'd end up excluding more than one package, maybe entire subtrees and not just leaves.

That said, I agree with you about that issue but in any case, if your project works is thanks to those packages, (un)fortunately.
